### ISSUE TITLE
Не могу настроить клиента nekoray на винде - x509: certificate is valid for www.google.com, not www.bing.com

### ISSUE THREAD

**Issue by Laser42** [EvgenyNerush/easy-xray#11]
Следую инструкции https://github.com/EvgenyNerush/easy-xray/blob/main/Nekoray.ru.md

Получаю ошибку
```
2024/06/13 08:52:44 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [x509: certificate is valid for www.google.com, not www.bing.com dial tcp ***.***.***.***:443: i/o timeout] > common/retry: all retry attempts failed
2024/06/13 08:52:44 [Warning] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [x509: certificate is valid for www.google.com, not www.bing.com dial tcp ***.***.***.***:443: i/o timeout] > common/retry: all retry attempts failed
```
instagram не открывается, хотя пинги идут.

Пробовал с галкой Системный прокси, Системный прокси+TUN, сам nekoray запускаю под администратором

Нашел вот эти советы https://github.com/v2fly/v2ray-core/issues/1873
- отключил проверку TLS Сертов в настройках, результат не изменился
- через telnet проверил - коннектится.

**Comment by EvgenyNerush** [comment]
А другие клиенты пробовали? На телефоне, например? В nekoray вы вставляете vless-ссылку, сгенерированную в easy-xray? Ссылка содержит коюч (между vless:// и @)?

**Comment by Laser42** [comment]
@EvgenyNerush да, у меня давно на телефоне стоит v2rayNG. На компе пытаюсь под тем же клиентом зайти. Ключ в ссылке содержится

**Comment by EvgenyNerush** [comment]
Ядро - xray? https://github.com/EvgenyNerush/easy-xray/blob/main/figs/nekoray-1.jpg

**Comment by EvgenyNerush** [comment]
V2rayN не пробовали? https://github.com/EvgenyNerush/easy-xray/blob/main/V2RayN.ru.md

**Comment by Laser42** [comment]
> Ядро - xray? https://github.com/EvgenyNerush/easy-xray/blob/main/figs/nekoray-1.jpg

Да, в точности следовал вашей инструкции

**Comment by Laser42** [comment]
> V2rayN не пробовали? https://github.com/EvgenyNerush/easy-xray/blob/main/V2RayN.ru.md

Гляну, попробую. Спасибо

**Comment by Laser42** [comment]
проблема решена, спасибо))
