### ISSUE TITLE
Скрытая клиентская конфигурация love@xray.com в config_server.json

### ISSUE THREAD

**Issue by momai** [EvgenyNerush/easy-xray#15]
Я поднял сервер по скрипту и обнаружил в config_server.json описание конфигурации клиента, которого я не описывал.

```
        "clients": [
          {
            "id": "e5ffefe3-5a9a-4288-a733-6480bf853a37",
            "email": "love@xray.com",
            "flow": "xtls-rprx-vision"
          },
```
Скажите, откуда взялся этот клиент? Я смог сформировать по нему ссылку и подключиться к впн.

Выглядит очень подозрительно.

**Comment by DevOps-spb-ru** [comment]
> 
> Скажите, откуда взялся этот клиент? Я смог сформировать по нему ссылку и подключиться к впн.
> 
> Выглядит очень подозрительно.
В исходном коде: https://github.com/EvgenyNerush/easy-xray/blob/41c67a2c0d6611c3dea6e25a06651c89aad2d0cd/ex.sh#L227

**Comment by momai** [comment]
Ок, спасибо, да. Однако непонятно для каких целей этот блок присутствует в конфигурации.

**Comment by EvgenyNerush** [comment]
Это дефолтный клиент, соответствующий конфигу conf/config_client.json. Из этого конфига делаются другие клиентские конфиги - в этом его смысл. Да, его также можно использовать для подключения, ничег плохого в этом не вижу. Пара ключей генерируется вами, поэтому использовать этого клиента никто, кроме вас, не сможет.

**Comment by momai** [comment]
Спасибо
