### ISSUE TITLE
Проблема с доступом с Android клиентов

### ISSUE THREAD

**Issue by dmitri-danilov** [EvgenyNerush/easy-xray#16]
Добрый день,

Поднял и сконфигурил сервер по скрипту. Полёт в целом нормальный, протестировал с разных платформ. Недоумение вызвал Android - из всех обнаруженных клиентов, полноценно заработал только NekoBox, во всех остальных случаях симптоматика схожая - после добавления сервера устанавливаю соединение, но доступ в интернет с устройства пропадает. Картина идентичная на Android TV (FireTV stick), и на смартфоне. Все настройки клиентов дефолтовые. 
Есть подозрение на какой-то параметр, который не является критичным для NekoBox, но блокирует доступ в интернет с других клиентов. Но что это может быть - в ходе многочисленных экспериментов понять пока не удалось.

Спасибо

**Comment by tand90** [comment]
Добрый день!

Появилась такая же проблема и никак не могу найти решение. Пробовал различные параметры подключения и ничего не помогает. Вы нашли решение?

**Comment by dmitri-danilov** [comment]
> Добрый день!
> 
> Появилась такая же проблема и никак не могу найти решение. Пробовал различные параметры подключения и ничего не помогает. Вы нашли решение?

Добрый!

Нашёл, и долго ржал над собой, т.к. решение у Евгения в РИДМИ файликах:

https://github.com/EvgenyNerush/easy-xray/blob/main/V2RayNG.ru.md
https://github.com/EvgenyNerush/easy-xray/blob/main/HiddifyNG.en.md

После нехитрых описанных манипуляций всё заработало на всех клиентах (включая Amnezia). Добавлю от себя про Hiddify (который next, не NG) - там в Remote DNS надо udp://1.1.1.1 поменять на tcp://1.1.1.1. Правда с этим клиентом есть одно "но" - у них до сих пор не реализованы исключения для обхода ВПН.

P.S. На самом деле, в V2RayNG вместо удаления '1.1.1.1' в Remote DNS можно его исправить в 'tcp://1.1.1.1'
