### ISSUE TITLE
Не работает ютуб через приложение IOS

### ISSUE THREAD

**Issue by garryly4** [EvgenyNerush/easy-xray#19]
Установил все по инструкции. На IOS поставил Streisand. Все ресурсы стали грузится, утуб в браузере тоже. Но вот через прилоежение не работает. Причем достаточно быстро грузятся комментарии, обложки рекомендуемых видео, но вот сам видео поток не грузится. В чем может быть проблема?

**Comment by EvgenyNerush** [comment]
Если вы добавляли googleapis dot com в список доменов для прямого доступа, то попробуйте его удалить. Также попробуйте включить Dns over https или dns over tls в системе (Doh, частный dns).
