### ISSUE TITLE
localhost not defined

### ISSUE THREAD

**Issue by Sverxsro4nik** [EvgenyNerush/easy-xray#22]
Добрый день. Выполнил все необходимые шаги по настройке сервера, нос толкнулся с проблемой что при запущенном сервисе блокируется адрес для localhost? Есть способ решить данную проблему?

**Comment by EvgenyNerush** [comment]
Что именно происходит? Что пишет при попытке запуска xray?
```
sudo xray -c conf/config_server.json
```

При запущенном xray, что показывает команда `sudo ss -tunlp`?

**Comment by Sverxsro4nik** [comment]
Прощу прощения, не правильно выразился. Блокируются запросы отправляемые на ru сегмент

**Comment by EvgenyNerush** [comment]
Извините, что так долго не отвечал. Гораздо быстрее отвечаю в телеграме (ссылка на странице проекта и в readme). Сервер специально блокирует .ру сайты - потенциально они могут вычислять использование прокси и передавать адрес в ркн. Российские сайты следует открывать напрямую, для этого можно прописать маршруты в клиенте. Смотрите инструкцию для конкретного клиента. Например для V2rayNG (Android) - здесь https://github.com/EvgenyNerush/easy-xray/blob/main/V2RayNG.ru.md
