### ISSUE TITLE
Streisand

### ISSUE THREAD

**Issue by leffffka** [EvgenyNerush/easy-xray#6]

**Comment by leffffka** [comment]
Установил приложение по инструкции и настроил роутинг на российские сайты. Если роутинг не включаю - приложение работает хорошо. При включении роутинга приложение разрывает соединение через 5 секунд. Можете помочь?
Проверял на двух устройствах с IOS и на iPad.

**Comment by EvgenyNerush** [comment]
О проблеме знаю, но решения пока нет. Можете попробовать FoXray и V2Box, но, говорят, проблема и там встречается.

**Comment by leffffka** [comment]
Спасибо.

**Comment by denis7502** [comment]
Мне помогло полная очистка всего в приложение через настройки и новый импорт всего

**Comment by EvgenyNerush** [comment]
Спасибо за решение!

**Comment by rewoop** [comment]
Привет! Проблема актуальна. Очистка всего не помогла

**UPD:** Удалил строку `geosite:cn,` первую из списка доменов и это помогло

**Comment by leffffka** [comment]
После очистки всего и удаления строки geosite:cn приложение перестало вылетать, но роутинг напрямую на российские сайты не работает.

**Comment by oohoow** [comment]
> После очистки всего и удаления строки geosite:cn приложение перестало вылетать, но роутинг напрямую на российские сайты не работает.

попробуй загрузить роутинг на русские сайты с этой ссылки: streisand://aW1wb3J0L3JvdXRlOi8vWW5Cc2FYTjBNRERWQVFJREJBVUdEQmdaR2xWeWRXeGxjMTFrYjIxaGFXNU5ZWFJqYUdWeVZHNWhiV1ZlWkc5dFlXbHVVM1J5WVhSbFozbFVkWFZwWktJSEV0TUlDUW9MREExYmIzVjBZbTkxYm1SVVlXZGRaRzl0WVdsdVRXRjBZMmhsY2xaa2IyMWhhVzVXWkdseVpXTjBWbWg1WW5KcFpLUU9EeEFSWG5KbFoyVjRjRG91S2x3dWNuVWtYeEFRWjJWdmMybDBaVHAzYUdGMGMyRndjRjFuWlc5emFYUmxPbUZ3Y0d4bFh4QVFaMlZ2YzJsMFpUcDBaV3hsWjNKaGJkTVRGQlVXREF0U2FYQmRaRzl0WVdsdVRXRjBZMmhsY2x0dmRYUmliM1Z1WkZSaFo2RVhXR2RsYjJsd09uSjFVbEpWWEVsUVNXWk9iMjVOWVhSamFGOFFKRVpGUkVWRU5USkZMVEl6TkRBdE5EUTJOaTA1TVRORExVSTJSVGMzTkRnd09FSXdNZ0FJQUJNQUdRQW5BQ3dBT3dCQUFFTUFTZ0JXQUdRQWF3QnlBSGtBZmdDTkFLQUFyZ0RCQU1nQXl3RFpBT1VBNXdEd0FQTUJBQUFBQUFBQUFBSUJBQUFBQUFBQUFCc0FBQUFBQUFBQUFBQUFBQUFBQUFFbg==


P.S. кажется, парсер не может корректно разобрать строку с доменами, которые грузим с https://github.com/EvgenyNerush/easy-xray/blob/main/misc/customgeo4hiddify.txt
