### ISSUE TITLE
Не работает Instagram

### ISSUE THREAD

**Issue by Nsenixx** [EvgenyNerush/easy-xray#9]
.

**Comment by EvgenyNerush** [comment]
На iOS такое уже замечали, но с чем это связано - я не знаю. На Android система иногда умудряется пускать dns-запросы не через прокси, несмотря на все настройки. Эти dns-запросы, естественно, блокируются, и сайты оказываются недоступными. На Android решается включением "частного dns", см. https://github.com/EvgenyNerush/easy-xray/issues/8#issuecomment-2039765472

**Comment by EvgenyNerush** [comment]
Еще можно посмотреть, нет ли лишнего в General -> VPN DNS на проблемном клиенте. Если есть лишнее, старое, ненужное - удалить.

**Comment by slavkapiyavka** [comment]
@Nsenixx привет! решили проблему?

**Comment by Nsenixx** [comment]
.

**Comment by EvgenyNerush** [comment]
ok
